name: TG Notification
on:
  push:
  pull_request:
  release:
    types: [published]
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_CHESSVIEW }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🚀 **Event in ${{ github.repository }}**
            
            Action by: ${{ github.actor }}
            Event Type: ${{ github.event_name }}
            
            ${{ github.event_name == 'push' && format('Commit: {0}', github.event.head_commit.message) || '' }}
            ${{ github.event_name == 'pull_request' && format('PR: {0}', github.event.pull_request.title) || '' }}
            ${{ github.event_name == 'release' && format('New Release: {0}', github.event.release.tag_name) || '' }}
            ${{ github.event_name == 'issues' && format('Issue: {0}', github.event.issue.title) || '' }}
            
            Link: ${{ github.event.release.html_url || github.event.pull_request.html_url || github.event.issue.html_url || github.event.head_commit.url }}
